### ISSUE TITLE
Thanks and overlay only part of the window?

### ISSUE THREAD

**Issue by rdiaz02** [ikn/xorg-choose-window#4]
Thanks a lot!!
And a question: is it possible to make the overlay cover only part of the window, so that the rest of the window is visible?

**Comment by gandalf3** [comment]
Hello, I've added customization options (as well as some other changes such as support for argb) to my fork: https://github.com/gandalf3/xorg-choose-window/tree/riceify. If there is any interest in merging any of those changes here I'd be happy to make a pull request!
